/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from 'ethers'
import type { BaseVoting, BaseVotingInterface } from '../BaseVoting'

const _abi = [
  {
    inputs: [],
    name: 'FailedToCallVerifyProof',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256[]',
        name: 'pubSignals',
        type: 'uint256[]',
      },
      {
        components: [
          {
            internalType: 'uint256[2]',
            name: 'a',
            type: 'uint256[2]',
          },
          {
            internalType: 'uint256[2][2]',
            name: 'b',
            type: 'uint256[2][2]',
          },
          {
            internalType: 'uint256[2]',
            name: 'c',
            type: 'uint256[2]',
          },
        ],
        internalType: 'struct AQueryProofExecutor.ProofPoints',
        name: 'zkPoints',
        type: 'tuple',
      },
    ],
    name: 'InvalidCircomProof',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'bytes32[]',
        name: 'pubSignals',
        type: 'bytes32[]',
      },
      {
        internalType: 'bytes',
        name: 'zkPoints',
        type: 'bytes',
      },
    ],
    name: 'InvalidNoirProof',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'registrationSMT',
        type: 'address',
      },
      {
        internalType: 'bytes32',
        name: 'registrationRoot',
        type: 'bytes32',
      },
    ],
    name: 'InvalidRegistrationRoot',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256[]',
        name: 'pubSignals_',
        type: 'uint256[]',
      },
    ],
    name: 'InvalidZKProof',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'previousAdmin',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'address',
        name: 'newAdmin',
        type: 'address',
      },
    ],
    name: 'AdminChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'beacon',
        type: 'address',
      },
    ],
    name: 'BeaconUpgraded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint8',
        name: 'version',
        type: 'uint8',
      },
    ],
    name: 'Initialized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'implementation',
        type: 'address',
      },
    ],
    name: 'Upgraded',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'registrationRoot_',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: 'currentDate_',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: 'userPayload_',
        type: 'bytes',
      },
    ],
    name: '_afterVerify',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'registrationRoot_',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: 'currentDate_',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: 'userPayload_',
        type: 'bytes',
      },
    ],
    name: '_beforeVerify',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'registrationRoot_',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: 'currentDate_',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: 'userPayload_',
        type: 'bytes',
      },
    ],
    name: '_buildPublicSignals',
    outputs: [
      {
        internalType: 'uint256',
        name: 'dataPointer_',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'registrationRoot_',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: 'currentDate_',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: 'userPayload_',
        type: 'bytes',
      },
      {
        components: [
          {
            internalType: 'uint256[2]',
            name: 'a',
            type: 'uint256[2]',
          },
          {
            internalType: 'uint256[2][2]',
            name: 'b',
            type: 'uint256[2][2]',
          },
          {
            internalType: 'uint256[2]',
            name: 'c',
            type: 'uint256[2]',
          },
        ],
        internalType: 'struct AQueryProofExecutor.ProofPoints',
        name: 'zkPoints_',
        type: 'tuple',
      },
    ],
    name: 'execute',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'registrationRoot_',
        type: 'bytes32',
      },
      {
        internalType: 'uint256',
        name: 'currentDate_',
        type: 'uint256',
      },
      {
        internalType: 'bytes',
        name: 'userPayload_',
        type: 'bytes',
      },
      {
        internalType: 'bytes',
        name: 'zkPoints_',
        type: 'bytes',
      },
    ],
    name: 'executeNoir',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getRegistrationSMT',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getVerifier',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'implementation',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proposalsState',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'proxiableUUID',
    outputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newImplementation',
        type: 'address',
      },
    ],
    name: 'upgradeTo',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newImplementation',
        type: 'address',
      },
      {
        internalType: 'bytes',
        name: 'data',
        type: 'bytes',
      },
    ],
    name: 'upgradeToAndCall',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
] as const

export class BaseVoting__factory {
  static readonly abi = _abi
  static createInterface(): BaseVotingInterface {
    return new Interface(_abi) as BaseVotingInterface
  }
  static connect(address: string, runner?: ContractRunner | null): BaseVoting {
    return new Contract(address, _abi, runner) as unknown as BaseVoting
  }
}
